apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: register-cluster
  annotations:
    policies.kyverno.io/title: Argo Cluster Secret Registration
    policies.kyverno.io/category: Argo
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Cluster
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy registers newly created crossplane clusters with ArgoCD
spec:
  background: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: generate-secret
      match:
        any:
        - resources:
            kinds:
            - eks.aws.upbound.io/v1beta1/Cluster
      preconditions:
        all:
        - key: "{{ request.object.status.atProvider.status }}"
          operator: Equals
          value: ACTIVE
      context:
      - name: clusterName
        variable:
          value: "{{ request.object.metadata.name }}"
      - name: ownerAccountId
        variable:
          value: "844333597536"
      - name: extraLabels
        variable:
          value:
            argocd.argoproj.io/secret-type: cluster
            clusterId: "{{ clusterName }}"
            clusterType: "tenant" 
      - name: serverName
        variable:
          value: "{{  request.object.status.atProvider.endpoint || 'none' }}"
      - name: caData
        variable:
          value: "{{ request.object.status.atProvider.certificateAuthority[0].data || 'none' }}"
      - name: roleARN
        variable:
          value: "arn:aws:iam::844333597536:role/npm-customer-demo-crossplane-role"
      - name: dataConfig
        variable:
          value: |
            {
              "awsAuthConfig": {
                  "clusterName": "{{ clusterName }}",
                  "roleARN": "{{ roleARN }}"
            },
              "tlsClientConfig": {
                "insecure": false,
                "caData": "{{ caData }}"
              }
            }     
          jmesPath: 'to_string(@)'
      generate:
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: "{{ clusterName }}-secret"
        namespace: argocd
        data:
          metadata:
            annotations:
              managed-by: argocd.argoproj.io              
            labels:
              "{{ extraLabels }}"
          type: Opaque
          data:
            name: "{{ clusterName | base64_encode(@) }}"
            server: "{{ serverName | base64_encode(@) }}"
            config: "{{ dataConfig | base64_encode(@) }}"
