---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-scans
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-all
      match:
        resources:
          kinds:
            - Pod
      context:
      - name: known-vulnerabilities
        attestation:
          predicateType: "https://nirmata.io/scan/v1"
          failurePolicy: Ignore
      verifyImages:
      - imageReferences:
        - "*"
        attestors:
        - entries:
          - keys: 
              publicKeys: "{{ keys.data.production }}"
        attestations:
        - predicateType: "https://nirmata.io/scan/v1"
          conditions:
          - any:
            - key: "{{ matches[].vulnerability | [?severity=='High' || severity=='Critical'].id | length(@) }}"
              operator: Equals
              value: 0
            - key: "{{ matches[].vulnerability | [?severity=='High' || severity=='Critical'].id }}"
              operator: In
              value: "{{ known-vulnerabilities.id }}"