---
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-image-notary
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: verify-signature-notary
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - type: NotaryV2
        imageReferences:
        - "jimnotarytest.azurecr.io/jim/net-monitor*"
        attestors:
        - count: 1
          entries:
          - certificates:
              cert: |-
                -----BEGIN CERTIFICATE-----
                MIIDVjCCAj6gAwIBAgIBUTANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQGEwJVUzEL
                MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEb
                MBkGA1UEAxMSd2FiYml0LW5ldHdvcmtzLmlvMB4XDTIzMDExODA2MDg0NloXDTIz
                MDExOTA2MDg0NlowWjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQH
                EwdTZWF0dGxlMQ8wDQYDVQQKEwZOb3RhcnkxGzAZBgNVBAMTEndhYmJpdC1uZXR3
                b3Jrcy5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOv75euYW+uq
                WWAz+Y4Oh+F0DfPeQ3ZqnGGUUllwtLe3q9ms4vJbq9qwHHga0jyF12511IphrrjH
                OBRtQFTIikPAJ3rZMCQiUjbUQDFNyqgoQx36/e3MyehUfPfEIKHhzNPR/iZ7KnTX
                EbIfYCKF8OpNWfnDjfafbJeY8dlMyf2Hv9a9riKGLxQ4Rie47MSxXOZz8DuHH/EJ
                e1RzWUdgcspSwxaC9kEebES8rQwkuVnHxrbXHpNnAy0dPRECCkvzEGRW73/vzGVC
                PNYK6ASVT7kj+8dYl5VDfKIhwzsPTQETeeziA9DpqLAs58DSaJQJ+89eGxgeMJkk
                llkW9dWXZEsCAwEAAaMnMCUwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsG
                AQUFBwMDMA0GCSqGSIb3DQEBCwUAA4IBAQAq/visaX+TKG//EVAM4bxtmsNVWCNu
                mnBeeMEMHuVH0qDTtvSSThTXjPF8+EUkRf8VETg1Lu4Lany0SWCZuih9FQ7KYeYt
                YS1PUXhIggpB0bGarWA+wePicTF4/4ngUUO4bg4Qhk/Biy1I0QHShpETp+bk6sJX
                k40GyNsSjDOIcEJ4KydhKkiAHQsobt4NlGOlgq2n/jA7tcNkHQ0oxHbmMcIdtYal
                cnCNpC8Ex6cx4ryQ7AhcLkREY4iQ9VuoP7/gUHGtqx+H1JHcsL4UIG4RXHE3MH4x
                i+5OrxPxFoZoP9Fec5CHoqyqHARziLhSLtQoipJL1Mq5z3VnAFQMgkP8
                -----END CERTIFICATE-----
