---
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-image-notary
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: verify-signature-notary
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - type: NotaryV2
        imageReferences:
        - "jimnotarytest.azurecr.io/jim/net-monitor*"
        attestors:
        - count: 1
          entries:
          - certificates:
              cert: |-
                -----BEGIN CERTIFICATE-----
                MIIDVjCCAj6gAwIBAgIBSDANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQGEwJVUzEL
                MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEb
                MBkGA1UEAxMSd2FiYml0LW5ldHdvcmtzLmlvMB4XDTIzMDIyMDAyMTQzMloXDTIz
                MDIyMTAyMTQzMlowWjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQH
                EwdTZWF0dGxlMQ8wDQYDVQQKEwZOb3RhcnkxGzAZBgNVBAMTEndhYmJpdC1uZXR3
                b3Jrcy5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDQgEm3gO0s
                3dX3LZvltjpGfmVSan9skMpGH98Vn8h1IlkaKIoTTpz3J9Pw0Vc95Z2kLmCnLue9
                n+4I6rDJO9aVG6GxsV8F42Rw7iEt90QVXAFhRZPOwWRlASGuuH5Ynicwfi3CbKaU
                4XaFwVdRKhiIAwluGQt4hCLWnAR5IgVtfRimNDjVp7H7QBsJOCoJz61bQu4zgZl4
                89uVeb9JapayVuqO7a2aYblXeIhCCBaIrWe386q/+i3LbaNpYYefJEpUGMyG/Vaw
                n4tHPP4AfyZ0uGcCh+sDxUfb2prI8nfjjj5awFC5277lueheRBqf4zhc3knPOUdd
                7e8TltmyQTMCAwEAAaMnMCUwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsG
                AQUFBwMDMA0GCSqGSIb3DQEBCwUAA4IBAQBAKeZKi0UNpRmUBLHiME//4EElO6qr
                mNlYFTGkCdEhPPIn6pp922u6En/uu0HPq9I6rPuTTOU6yrVeb2HmlWLXT6DHvxRI
                zcDbHN+6MHCGAfcIHempK/Y8PDF/euvYknoWX9ScOZBwqPNmsx5VNjApVMx0lA/6
                v3iiMckrG/Fk949TPQ/h2BlGAiw7mY3kgw6ZJfZZr2xmEyO/8ua4K//1WIzIljdT
                XlGkLhwXkLUUg7nJYAyWeWp87GtFCLSK98bIPuxak9d4e8X2zfqBk9vQMdc9ZNVl
                Q14yAHUcWvaNxOztdlUjQFFbYAQXd3GU5ZJ8QuI30yf5vbbjB8WISvXe
                -----END CERTIFICATE-----
