apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-image-notary
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: verify-signature-notary
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces: ["octank"]
      verifyImages:
      - type: NotaryV2
        imageReferences:
        - "jimnotarytest.azurecr.io/jim/net-monitor:v1"
        attestors:
        - count: 1
          entries:
          - certificates:
              cert: |-
                -----BEGIN CERTIFICATE-----
                MIIDVjCCAj6gAwIBAgIBUTANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQGEwJVUzEL
                MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEb
                MBkGA1UEAxMSd2FiYml0LW5ldHdvcmtzLmlvMB4XDTIyMTEyNzIwMTEyOFoXDTIy
                MTEyODIwMTEyOFowWjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQH
                EwdTZWF0dGxlMQ8wDQYDVQQKEwZOb3RhcnkxGzAZBgNVBAMTEndhYmJpdC1uZXR3
                b3Jrcy5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALpon2kaJo1C
                obUxF7yjGoduLGaikjXwS75wwAWQOYEKzstWbyspu/Zlu7KOObVwOgM0tFmrpTfk
                +tKJ/U1Aq2OSaYRspGKhGf/ZRJNEcMIAZ5mVxdy+QlQ8a7215KQ2lv7Lhb22RMuK
                wFbn3FgZSLBvVpiQbnCn2CtCFn2GX4MN7ewVhhuOsCfTJw/ZFKwWMe7GoOnqKbAK
                +xo+FMABMUaSF2XkJE/db1gjcO/ah2+wfxLmdkgmqqXdzN97RA1JSnhrFsol2I2h
                2o0cK0CgyxOinBktrJhiZISlo2tph1v4DIBfgJoQPUtp3YjznguCU/TtD9JcZt+L
                qaCcHsyQWpMCAwEAAaMnMCUwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsG
                AQUFBwMDMA0GCSqGSIb3DQEBCwUAA4IBAQBpiheCWLILPG1PCP8mVNFJD19imlQM
                Ub2daLgivN9VCAR3V0vDmgjrtFzmFzHscD1YmdInCY4Xga9JkuSac78rxc9qW+PU
                MkV54BnR0O/ZA4YoJCxccPlYSledSbL1GKaFNoc8BhYbHlCouh6NDp4oE9NtL4Ye
                MHW+coovXYXIUpMUz0FlkfFL3a3BxkONqS4P0tLnU692MwiGAT2BxddADk4uWFIy
                H2Uj2VIoyD2VikqcCe5vaGt2v7iEgGYZFs/3OS58pIxPCbqUrIte+mY0UlZwoqaY
                SVUxzyhTZCQaU4d8YfUyErahg+M530OXvt3HfJgt3FD8CWWQ9W1CtODg
                -----END CERTIFICATE-----