apiVersion: apps/v1
kind: Deployment
metadata:
  name: distress-busybox
  namespace: existing
  labels:
    app: distress-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distress-busybox
  template:
    metadata:
      labels:
        app: distress-busybox
    spec:
      containers:
      - image: busybox:1.28
        name: busybox
        command: [sleep, 10s]