apiVersion: v1
kind: Pod
metadata:
  name: test-hp
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/data
      # this field is optional
      type: Directory