apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: allow-insecure-pod
  namespace: kyverno
spec:
  match:
    any:
      - resources:
          names:
            - "nginx"
          namespaces:
            - test
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames: ["*"]
    - policyName: disallow-privilege-escalation
      ruleNames: ["*"]
    - policyName: require-run-as-nonroot
      ruleNames: ["*"]
    - policyName: restrict-seccomp-strict
      ruleNames: ["*"]

