---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-keyless
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-image-keyless
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/jimbugwadia/demo-java-tomcat:*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/JimBugwadia/demo-java-tomcat/.github/workflows/publish.yaml@refs/tags/*"
              issuer: "https://token.actions.githubusercontent.com"
              additionalExtensions:
                githubWorkflowTrigger: push
                githubWorkflowSha: 73f9df28b6c67e3d4a4ffc4b75aaeed89be88b58
                githubWorkflowName: build-sign-attest
                githubWorkflowRepository: JimBugwadia/demo-java-tomcat
