apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-sbom-attestations
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-sbom
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/chipzoller/zulu:*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/chipzoller/zulu/.github/workflows/slsa-generic-keyless.yaml@refs/tags/v*"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: https://cyclonedx.org/schema
          conditions:
          - all:
            - key: "{{ Data.bomFormat }}"
              operator: Equals
              value: CycloneDX