---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-scan
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  applyRules: One
  rules:
    - name: check-attestions-tomcat
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/jimbugwadia/demo-java-tomcat:v0.0.16"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/JimBugwadia/demo-java-tomcat/.github/workflows/publish.yaml@refs/tags/*"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: "https://trivy.aquasec.com/scan/v2"
          conditions:
          - all:
            - key: "{{ Results[].Vulnerabilities[?CVSS.redhat.V3Score >= `10.0`][] | length(@) }}"
              operator: Equals
              value: 0
    - name: check-attestions-default
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/JimBugwadia/demo-java-tomcat/.github/workflows/publish.yaml@refs/tags/*"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: "https://trivy.aquasec.com/scan/v2"
          conditions:
          - all:
            - key: "{{ Results[].Vulnerabilities[?CVSS.redhat.V3Score >= `8.0`][] | length(@) }}"
              operator: Equals
              value: 0
