apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: eng
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox:1.35
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: platform
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox:1.35
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: existing
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox:1.35
    name: busybox