apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: time-based-policy
spec:
  background: false
  validationFailureAction: Enforce
  rules:
    - name: disallow-priv-escalation-in-business-hours
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
          # Get the hour of the current time
        - key: "{{ time_now_utc().time_to_cron(@).split(@,' ') | [1].to_number(@) }}"
          operator: AnyIn
          # Only operate during business hours, 8am-5pm EST, in UTC
          value: 13-22
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation,
          and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to `false`.
        pattern:
          spec:
            =(ephemeralContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            =(initContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            containers:
            - securityContext:
                allowPrivilegeEscalation: "false"