apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
metadata:
  annotations:
    policies.kyverno.io/description: "Allow creating S3 bucket in us-west-2 only"
    pod-policies.kyverno.io/autogen-controllers: "none"
    policies.kyverno.io/subject: "Bucket"
    policies.kyverno.io/title: "Allow creating S3 bucket in us-west-2 only"
  name: "allow-us-west-2-only"
spec:
  validationFailureAction: "Enforce"
  background: true
  rules:
  - name: "s3-in-us-west-2-only"
    match:
      resources:
        kinds:
        - "Bucket"
    validate:
      pattern:
        spec:
          forProvider:
            region: "us-west-2"
      message: "location {{ request.object.spec.forProvider.region }} is not allowed"