apiVersion: v1
data:
  # 100bf38cc8393103870917dd535e0628
  token: MTAwYmYzOGNjODM5MzEwMzg3MDkxN2RkNTM1ZTA2Mjg=
kind: Secret
metadata:
  name: bluesecret
  namespace: existing
  labels:
    kyverno.io/watch: "true"
type: Opaque
