apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: important-tool
  namespace: default
spec:
  automountServiceAccountToken: false
  hostIPC: true
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - 1d